version: "3"

services:
  app:
    restart: unless-stopped
    image: web-archive-archive-viewer
    build: .
    command: '/websites http://+:8080/'
    ports:
      - 8080:8080
    volumes:
      - "./websites:/websites:ro"